"""change model hashed_password to password

Revision ID: 856f45aa30fa
Revises: 2f7e42b351ca
Create Date: 2025-11-13 16:27:07.085447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '856f45aa30fa'
down_revision: Union[str, Sequence[str], None] = '2f7e42b351ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('app_users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('app_users', 'password')
    # ### end Alembic commands ###
